### ISSUE TITLE
Is that a working Hcloud provider for ClusterAPI?

### ISSUE THREAD

**Issue by gris-gris** [Freggy/cluster-api-provider-hcloud#1]
Hello, just searched for the hcloud providers around GitHub and found that your repository is fresh while official provider seems like abandoned.

Are you planning to work on provider v1beta1? Because official won't work with the latest ClusterAPI version:
`Error: current version of clusterctl is only compatible with v1beta1 providers, detected v1alpha3 for provider infrastructure-hcloud`

**Comment by Freggy** [comment]
Yes, I intend to implement `v1beta1`

**Comment by gris-gris** [comment]
Are you going to contribute that in https://github.com/cluster-api-provider-hcloud/cluster-api-provider-hcloud ?

**Comment by gris-gris** [comment]
Or will go separate way?

**Comment by Freggy** [comment]
I will go the seperate way for now and push all the stuff related to the implementation of `v1beta1` to this repository.
